#!/bin/bash

USERNAME=$1

# Check for existing username
# Thanks, http://www.cyberciti.biz/tips/howto-write-shell-script-to-add-user.html
egrep "^$USERNAME" /etc/passwd >/dev/null
if [ $? -eq 0 ]; then
  echo "$USERNAME found..."
else 
  echo "$USERNAME does not exist!"
  exit 1
fi 

# create password: @TODO: how to assign and notify of a secure autogenerated password?
# PASSWORD=jkl4gh4jhgjui4o4y
PASSWORD=changemenow
PASSWORD_ENCRYPTED=$(perl -e 'print crypt($ARGV[0], "password")' $PASSWORD)

# Delete user
userdel -rf $USERNAME
echo "User $USERNAME has been deleted!"



